---
title: "R Notebook"
output: html_notebook
---

1.- Prueba de lanzamiento de una moneda
```{r}
moneda <- c("cara","sello")
sample(moneda, 2)
```


```{r}
# Lanzar la moneda 100 veces
sample(moneda, 100, T)
```

```{r}
# Contar la cantidad de veces
table(sample(moneda, 100, T))
```

```{r}
# Cuando aumenta la cantidad de pruebas 
# se acerca al punto teorico
table(sample(moneda, 10000000, T))
```

2.- Prueba de sacar 3 bolas de una bolsa 

```{r}
# Se define las bolsa
bolsa1 <- c("b","b","b","n","n","n")
bolsa2 <- c("b","b","b","r","r","r")

# Se saca una bola de cada bolsa
CON_REEMPLAZO <- F
item_b1 <- sample(bolsa1, 1, CON_REEMPLAZO)
item_b2 <- sample(bolsa2, 1, CON_REEMPLAZO)

item_b1
item_b2
```

```{r}
bolsa1
bolsa2
```

```{r}
bolsa1 <- c(bolsa1, item_b1)
bolsa1

```
```{r}
# Se define las bolsa
bolsa1 <- c("b","b","b","n","n","n")
bolsa2 <- c("b","b","b","r","r","r")

print("Bolsas iniciales")
bolsa1
bolsa2

pos_b1_item1 <- sample.int(6,1,F)
temp1 <- bolsa1[pos_b1_item1]

pos_b2_item1 <- sample.int(6,1,F)
temp2 <- bolsa2[pos_b2_item1]

bolsa1[pos_b1_item1] <- temp2
bolsa2[pos_b2_item1] <- temp1

print("Bolsas finales")
bolsa1
bolsa2

```

```{r}
pos_b2_item1 <- sample.int(6,2,F)
pos_b2_item1
```

3.- Lanzar 2 dados y obtener el maximo valor de la cara superior de los dados
```{r}
dado1 <- c(1,2,3,4,5,6)
dado2 <- c(1,2,3,4,5,6)
resultados <- c(sample(dado1,1,T), sample(dado2,1,T))
resultados
max(resultados)

```
```{r}
NRO_DADOS <- 2
dado <- c(1,2,3,4,5,6)
resultados <- sample(dado,NRO_DADOS)
resultados
max(resultados)
```

