---
title: "R Notebook"
output: html_notebook
---

```{r}
#Simulacion distribucion muestral de la media
poblacion1=rnorm(1000) # simula datos de una distribucion normal 
poblacion2=rexp(1000)  # simula datos de una distribucion exponencial

# datos : poblacion
# n : tamanho de la muestra
# m : numero de muestras
simulacion1 <- function(datos,n,m) {

  N=length(datos) # tamanho de la poblacion
  mu=mean(datos)  # calcula 
  sigma2=var(datos)*((N-1)/N)  # (N-1)/N : Factor de correcion
  resul=sigma2/n  # varianza de la media
  
  muestras=matrix(0,m,n) # m fila (muestras) y n columnas (datos de la muestra)
  
  print(muestras)
  
  # realiza "m" muestras
  for (i in 1:m)
    muestras[i,]=sample(datos,n,replace=T) # muestras con reemplazo y lo 
                                           # almacena en la fila "i"
  print(muestras)
  
  mediasm=apply(muestras,1,mean) # Calcula la media para cada fila (1)
  
  mediaxbar=mean(mediasm)        # Calcula la medias de las medias
  
  varxbar=var(mediasm)*((m-1)/m) # Calcula la varianza de las estimadas
  
  medias=c(mu,mediaxbar)        # mu es el valor teorico y mediaxbar es el estimado
  varianzas=c(resul,varxbar)    # resul es el valor teorico y varxbar es el estimado
  
  print(medias)
  print(varianzas)
  
  par(mfrow = c(1, 2))
  
  hist(datos)
  hist(mediasm)
}

# Ejecucion de la simulacion
#simulacion1(poblacion2, 100, 50)

simulacion1(poblacion2, 8, 5)

```
```{r}
# n1 y n2 tamanhos
# m : numero de repeticiones
simulacion2=function(datos1,datos2,n1,n2,m){
    N1=length(datos1)
    N2=length(datos2)
    mu1=mean(datos1)
    mu2=mean(datos2)
    mu=mu1-mu2
    
    sigma21 = var(datos1)*((N1-1)/N1)
    sigma22 = var(datos2)*((N2-1)/N2)
    resul = sigma21/n1 + sigma22/n2  # varianza ponderada
    
    # diferencia de muestras
    difer=rep(0,m)
    
    for (i in 1:m){
      muestras1=sample(datos1,n1,replace=T)
      muestras2=sample(datos2,n2,replace=T)
      #d=mean(muestras1)-mean(muestras2)
      #difer[i] = mean(d)
      difer[i] = mean(muestras1)-mean(muestras2)
    }
    
    mediasm = mean(difer)
    varxbar = var(difer)*((m-1)/m)
    medias = c(mu,mediasm)
    varianzas = c(resul,varxbar)
    
    print(medias)
    print(varianzas)
    hist(difer)
}
```

```{r}
women # ya existe esta matriz
```

```{r}

# women[,1] : height (tamanho)
# women[,2] : weight (peso)

# No tiene sentido esta ejecucion
simulacion2(women[,1], women[,2],59,54,100)  
```
```{r}
women1 <- women[1:8,1]
women2 <- women[9:15,1]

simulacion2(women1, women2, 59, 54, 100)  
```
```{r}
sample(c("car","sello"),20, replace=T)
```

